### ISSUE TITLE
Issuse Related about Calibration

### ISSUE THREAD

**Issue by mohdsaleem987** [lzx1413/AndroidMarkerARDemo#8]
Hello sir,
I am in new open cv. please help me about how we can run your project in ar mode with out calibration or how i set default value of camera calibration.

 if (mCalibrator.getCornersBufferSize() < 2) {
                    (Toast.makeText(this, res.getString(R.string.more_samples), Toast.LENGTH_SHORT)).show();
                    return true;
                }

how i set the mCalbrator.getCornerBufferSize() with some default value
if i am using  this code in  onCameraViewStarted
 mOnCameraFrameRender = new OnCameraFrameRender(new ARFramRender(mCalibrator,mWidth,mHeight,getResources()));
then preview starting calibration from left top corner of camera preview

**Comment by lzx1413** [comment]
The camera matrix is set as identity matrix as default here,https://github.com/lzx1413/AndroidMarkerARDemo/blob/71ff6b6d17c548a1e32b0f5328451194b8a29bd1/androidcalibration/src/main/java/com/example/lzx1413/androidcalibration/CameraCalibrator.java#L47. You can reset it as your wish.

**Comment by mohdsaleem987** [comment]
Hello Sir,
Thanks for the help,
I wanted to detect rectangle in camera preview and place some image on that place ,
In your code first calibrate the & save the camera matrix. i wanted to know how we can set some value in mCameraCalibration matrix and use this value to in c++ code to place our object
how i can detect rectangele or four edges of camera preview in android

**Comment by lzx1413** [comment]
You can do like this https://github.com/lzx1413/AndroidMarkerARDemo/blob/71ff6b6d17c548a1e32b0f5328451194b8a29bd1/androidcalibration/src/main/cpp/native-opencv.cpp#L102 to transport the camera mat from java to cpp with jni. You can load the matrix from a xml file or with hard code.

**Comment by mohdsaleem987** [comment]
we are using this concept to find out rectangle in camera & find out the contours & edges point
But we cannot apply camera calibration . Because if we place the ic_launcher on the rectangle place it never feel like a 3d view

**Comment by mohdsaleem987** [comment]
Hello Sir,
I think you doing very well , i solved out my problem as you are suggestion . But i wanted one more suggestion in your side like 
i find findMarkerCandidates method in markerdetector class in this method what changes i apply to detect the only square/rectangle because which has only four edges.

**Comment by mohdsaleem987** [comment]
hello sir 
why this error is comming 
 Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4) in cv::Mat cv::getPerspectiveTransform(cv::InputArray, cv::InputArray), file /build/master_pack-android/opencv/modules/imgproc/src/imgwarp.cpp, line 6748
please help me out
