### ISSUE TITLE
Android Oreo Problem

### ISSUE THREAD

**Issue by mohdsaleem987** [lzx1413/AndroidMarkerARDemo#9]
Hello Sir
In android oreo camera preview does not show tell me where is the problem....

**Comment by lzx1413** [comment]
Sorry, I don't have a device with android O :)

**Comment by mohdsaleem987** [comment]
hello sir when i placed a back tattoo image with transparent background the tattoo image does not show
Is there width & height create some problem ....

**Comment by lzx1413** [comment]
Maybe you can use the default camera2 api to preview the the camera images.

**Comment by mohdsaleem987** [comment]
cv::inRange(per_image, cv::Scalar(0, 0, 0, 255), cv::Scalar(255, 255, 255, 255), mask);
i found this code in map image method of idisplay.cpp file this code create problem when i plot full black transparent image into the find marker image

**Comment by mohdsaleem987** [comment]
hello sir ,
When i apply the inpaint process then apply plot cube then no cube image shown

**Comment by mohdsaleem987** [comment]
hello sir when i apply in paint process or when i change
cv::Mat in_mat(h,w,CV_8UC4,(unsigned char*) pixls);
to cv::Mat in_mat(h,w,CV_8UC1,(unsigned char*) pixls);
tattoo is not visible please tell me the problem..

**Comment by lzx1413** [comment]
The input of the image from the mobile is usually in the format of rbga, so 4 channels Mat is needed to handle the image data.

**Comment by mohdsaleem987** [comment]
cv::Mat inpaintMat = rgbimage;
    cvtColor(inpaintMat, inpaintMat, CV_BGR2RGB, 1);
    cvtColor(inpaintMat, inpaintMat, CV_RGB2BGR, 1);

and 

  cv::Mat contoursImage(rgbimage.size(), CV_8UC1, cvScalar(0));
  cv::drawContours(contoursImage, contours, i, cv::Scalar(255), 30, cv::LINE_8);
  inpaint(inpaintMat, contoursImage, rgbimage, 4, cv::INPAINT_NS);

After inpaint i add tattoo image but tattoo image is not shown then what i can do...
in i comment the inpaint line the plotted cube is shown please check and tell the solutions

**Comment by mohdsaleem987** [comment]
Hello Sir,
Please help me to plot cube image using opengl in android

**Comment by lzx1413** [comment]
opengl is more complex than opencv in this case, and I think opencv is enough to complete this task. you can run the code in  a project on PC to see where is the problem is.

**Comment by mohdsaleem987** [comment]
when i apply inpaint process to remove marker & after i plot the cube. cube is not visible 
when i comment the inpaint code cube is visible please tell me the problem...
